INSERT INTO Inventory VALUES ('Payless Beef 55g', 7, 'Instant noodles', 20);
INSERT INTO Inventory VALUES ('Mega 155g', 10, 'Canned goods', 20);
INSERT INTO Inventory VALUES ('Argentina Corned Beef 175g', 10, 'Canned goods', 20);
INSERT INTO Inventory VALUES ('Argentina Meat Loaf 150g', 10, 'Canned goods', 20);
INSERT INTO Inventory VALUES ('Century Tuna 180g', 10, 'Canned Goods', 20);
INSERT INTO Inventory VALUES ('Kopiko 10x27.5g', 4, 'Powdered drinks', 20);
INSERT INTO Inventory VALUES ('Tang', 24, 'Powdered drinks', 20);
INSERT INTO Inventory VALUES ('Maggi 25g', 20, 'Seasoning', 20);
INSERT INTO Inventory VALUES ('Milo 24g', 28, 'Powdered drinks', 20);
INSERT INTO Inventory VALUES ('Datu Puti Patis 350ml', 12, 'Seasoning', 20);
INSERT INTO Inventory VALUES ('Silver Swan 350g Suka', 12, 'Seasoning', 20);
INSERT INTO Inventory VALUES ('Silver Swan 350g Toyo', 12, 'Seasoning', 20);
INSERT INTO Inventory VALUES ('Sky Flakes 25g', 15, 'Biscuit', 20);
INSERT INTO Inventory VALUES ('Coke Mismo', 20, 'Softdrinks', 20);
INSERT INTO Inventory VALUES ('Sprite Mismo', 20, 'Softdrinks', 20);
INSERT INTO Inventory VALUES ('Royal Mismo', 20, 'Softdrinks', 20);
INSERT INTO Inventory VALUES ('Coke 1.5', 50, 'Softdrinks', 20);
INSERT INTO Inventory VALUES ('Sprite 1.5', 50, 'Softdrinks', 20);
INSERT INTO Inventory VALUES ('Royal 1.5', 50, 'Softdrinks', 20);
INSERT INTO Inventory VALUES ('Pancit Canton Chilimansi', 20, 'Instant noodles', 20);
INSERT INTO Inventory VALUES ('Pancit Canton Calamansi', 20, 'Instant noodles', 20);
INSERT INTO Inventory VALUES ('Pancit Canton Original', 20, 'Instant noodles', 20);
INSERT INTO Inventory VALUES ('Pancit Canton Sweet&Spicy', 20, 'Instant noodles', 20);
INSERT INTO Inventory VALUES ('Pancit Canton ExtraHot', 20, 'Instant noodles', 20);
INSERT INTO Inventory VALUES ('Chippy BBQ 25g', 7, 'Chips', 20);
INSERT INTO Inventory VALUES ('Chippy SourCream 25g', 7, 'Chips', 20);
INSERT INTO Inventory VALUES ('Chippy Mild&Tasty 25g', 7, 'Chips', 20);
INSERT INTO Inventory VALUES ('Chippy Chili&Cheese 25g', 7, 'Chips', 20);
INSERT INTO Inventory VALUES ('Piattos Cheese 40g', 15, 'Chips', 20);
INSERT INTO Inventory VALUES ('Piattos SourCream 40g', 15, 'Chips', 20);
INSERT INTO Inventory VALUES ('Piattos RoastBeef 40g', 15, 'Chips', 20);
INSERT INTO Inventory VALUES ('Piattos NachoPizza 40g', 15, 'Chips', 20);
INSERT INTO Inventory VALUES ('Piattos SpicyCheese 40g', 15, 'Chips', 20);
INSERT INTO Inventory VALUES ('Piattos SaltedPotato 40g', 15, 'Chips', 20);
INSERT INTO Inventory VALUES ('Ariel 100g', 28, 'Cleaning supply', 20);
INSERT INTO Inventory VALUES ('Tide 100g', 28, 'Cleaning supply', 20);
INSERT INTO Inventory VALUES ('Surf 100g', 28, 'Cleaning supply', 20);
INSERT INTO Inventory VALUES ('Pride 100g', 28, 'Cleaning supply', 20);
INSERT INTO Inventory VALUES ('Ariel 100g', 28, 'Cleaning supply', 20);
INSERT INTO Inventory VALUES ('Zonrox Fresh 250ml', 25, 'Cleaning supply', 20);
INSERT INTO Inventory VALUES ('Zonrox Floral 250ml', 25, 'Cleaning supply', 20);
INSERT INTO Inventory VALUES ('Zonrox Original 250ml', 25, 'Cleaning supply', 20);
INSERT INTO Inventory VALUES ('Zonrox Lemon 250ml', 25, 'Cleaning supply', 20);
INSERT INTO Inventory VALUES ('Zonrox Colorsafe 250ml', 28, 'Cleaning supply', 20);
INSERT INTO Inventory VALUES ('Pochi', 1, 'Candies', 20);
INSERT INTO Inventory VALUES ('Lollipop', 1, 'Candies', 20);
INSERT INTO Inventory VALUES ('SnowBear', 1, 'Candies', 20);
INSERT INTO Inventory VALUES ('Mentos', 1, 'Candies', 20);
INSERT INTO Inventory VALUES ('Frutos', 1, 'Candies', 20);
INSERT INTO Inventory VALUES ('Yakee', 1, 'Candies', 20);

SELECT * FROM Invetory